services:
  catalogdb:
    container_name: catalogdb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - catalogdb_volume:/data/db
  basketdb:
    container_name: basketdb
    restart: always
    ports:
      - "6379:6379"
  discountdb:
    container_name: discountdb
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - discountdb_volume:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=PassMass12*
      - POSTGRES_DB=discountdb
  messagedb:
    container_name: messagedb
    restart: always
    ports:
      - "5433:5432"
    volumes:
      - messagedb_volume:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=PassMass12*
      - POSTGRES_DB=messagedb
  cargodb:
    container_name: cargodb
    restart: always
    ports:
      - "5434:5432"
    volumes:
      - cargodb_volume:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=PassMass12*
      - POSTGRES_DB=cargodb
  commentdb:
    container_name: commentdb
    restart: always
    ports:
      - "27018:27017"
    volumes:
      - commentdb_volume:/data/db
  identitydb:
    container_name: identitydb
    restart: always
    ports:
      - "1433:1433"
    volumes:
      - identitydb_volume:/var/opt/mssql
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=PassMass12*
  orderdb:
    container_name: orderdb
    restart: always
    ports:
      - "1444:1433"
    volumes:
      - orderdb_volume:/var/opt/mssql
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=PassMass12*
  rabbitmq:
    container_name: rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
  catalog.api:
    container_name: catalog.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - IdentityServerURL=http://identityserver.api
      - DatabaseSettings:ConnectionString=mongodb://catalogdb:27017
    ports:
      - "5011:80"
    depends_on:
      - catalogdb
  identityserver.api:
    container_name: identityserver.api
    restart: on-failure
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ConnectionStrings:DefaultConnection=Server=identitydb,1433;Database=IdentityDb; User=sa; Password=PassMass12*"
    ports:
      - "5001:80"
    depends_on:
      - identitydb
  basket.api:
    container_name: basket.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - IdentityServerURL=http://identityserver.api
      - RedisSettings:Port=6379
      - RedisSettings:Host=basketdb
    ports:
      - "5013:80"
    depends_on:
      - basketdb
  photostock.api:
    container_name: photostock.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - IdentityServerURL=http://identityserver.api
      - Cloudinary_CloudName=di3v4p6pm
      - Cloudinary_ApiKey=553866489557771
      - Cloudinary_ApiSecret=JsIpPlFy8wu78mzaGJwsn-KYmkg
    ports:
      - "5016:80"
  discount.api:
    container_name: discount.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - IdentityServerURL=http://identityserver.api
      - "ConnectionStrings:PostgreSql=User ID=admin; Password=PassMass12*; Server=discountdb; Port=5432;Database=discountdb;Integrated Security=true;Pooling=true"
    ports:
      - "5014:80"
    depends_on:
      - discountdb
  message.api:
    container_name: message.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - IdentityServerURL=http://identityserver.api
      - "ConnectionStrings:PostgreSql=User ID=admin; Password=PassMass12*; Server=messagedb; Port=5432;Database=messagedb;Integrated Security=true;Pooling=true"
    ports:
      - "5019:80"
    depends_on:
      - messagedb
  cargo.api:
    container_name: cargo.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - IdentityServerURL=http://identityserver.api
      - "ConnectionStrings:PostgreSql=User ID=admin; Password=PassMass12*; Server=cargodb; Port=5432;Database=cargodb;Integrated Security=true;Pooling=true"
    ports:
      - "5017:80"
    depends_on:
      - cargodb
  comment.api:
    container_name: comment.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - IdentityServerURL=http://identityserver.api
      - DatabaseSettings:ConnectionString=mongodb://commentdb:27017
    ports:
      - "5018:80"
    depends_on:
      - commentdb
  order.api:
    container_name: order.api
    restart: on-failure
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - IdentityServerURL=http://identityserver.api
      - "ConnectionStrings:DefaultConnection=Server=orderdb,1433;Database=orderDb; User=sa; Password=PassMass12*"
    ports:
      - "5015:80"
    depends_on:
      - orderdb
  gateway.api:
    container_name: gateway.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - IdentityServerURL=http://identityserver.api
    ports:
      - "5000:80"