FROM mcr.microsoft.com/dotnet/sdk:3.1 as build
WORKDIR /app
EXPOSE 80

COPY IdentityServer/MicroServiceShop.IdentityServer/MicroServiceShop.IdentityServer.csproj IdentityServer/MicroServiceShop.IdentityServer/
RUN dotnet restore IdentityServer/MicroServiceShop.IdentityServer/MicroServiceShop.IdentityServer.csproj
COPY . .

RUN dotnet publish IdentityServer/MicroServiceShop.IdentityServer/MicroServiceShop.IdentityServer.csproj -c Release -o out

FROM mcr.microsoft.com/dotnet/aspnet:3.1 as runtime
WORKDIR /app
COPY --from=build /app/out .
ENTRYPOINT ["dotnet", "MicroServiceShop.IdentityServer.dll"]